site_name: WoodCore Documentation
nav:
  - Home: index.md
  - Documentation Review: review.md
  - "WoodCore Atlas API":
    - Reference: reference.md
    - Sorting: sorting.md
    - Versioning: versioning.md
    - Pagination: pagination.md
    - API Headers: API_headers.md
    - Response Codes: response_codes.md
    - Default Parameters: default_parameter.md
  - "Security":
      - "Security and Access":
          - Whitelist an IP Address: whitelist_address.md
          - Approved Whitelisted IP: whitelisted_ip.md
  - "Customer":
    - Customer Overview: Customer.md


theme:
  name: readthedocs
  pallette:
    scheme: light
    primary: indigo
    accent: deep-orange
    copy_button: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - codehilite

plugins:
  - search
