site_name: WoodCore Documentation
nav:
  - Home: index.md
  - Documentation Review: review.md
  - "WoodCore Atlas API":
    - Reference: reference.md
    - Sorting: sorting.md
    - Versioning: versioning.md
    - Pagination: pagination.md
    - API Headers: API_headers.md
  - "Customer":
    - Customer Overview: Customer.md


theme:
  name: readthedocs
  pallette:
    scheme: light
    primary: indigo
    accent: deep-orange
    copy_button: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - codehilite

plugins:
  - search
